[sqlfluff]
dialect = "bigquery"
templater = "jinja"
max_line_length = 100

[sqlfluff:indentation]
tab_space_size = 4

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = "upper"

[sqlfluff:rules:capitalisation.functions]
capitalisation_policy = "upper"

[sqlfluff:rules:aliasing.table]
aliasing = "explicit"
